
spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:http://localhost:8888


     # This line may also need a key
# mongodb+srv://nischalgautam7200:db_password>@cluster0.vlz65rp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0