server:
  port: 8084
spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  data:
    mongodb:
      uri: mongodb+srv://nischalgautam7200:nischal@cluster0.cahsgvf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: fitnessrecommendation
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}