spring:
  config: 
    import: optional:configserver
  datasource:
      url: jdbc:postgresql://localhost:5432/fitness_user_db
      username: postgres
      password: nischal
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
