spring:
  application:
    name: userservice
  datasource:
      url: jdbc:postgresql://localhost:5432/fitness_user_db
      username: postgres
      password: nischal
  jpa:
    hibernate:
      ddl-auto: update
    database-platorm: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081